version: "3.8"
services:
  demo-queue-ui:
    image: "siteslave/r7-queue-ui"
    container_name: "demo-queue-ui"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=192.168.1.11
      - REDIS_USERNAME=demo
      - REDIS_PASSWORD=demo
      - REDIS_PORT=6379
      - UI_USERNAME=xxxx
      - UI_PASSWORD=xxxx
      - KK_QUEUE_NAME=KHONKAEN
      - MSK_QUEUE_NAME=MAHASARAKHAM
      - ROIET_QUEUE_NAME=ROIET
      - KALASIN_QUEUE_NAME=KALASIN
      - SECRET_KEY=xxxx
      - SUPER_SECRET_KEY=xxxx
    ports:
      - 3333:3000   
    restart: always