version: "3.8"
services:
  demo-queue-ui:
    image: "registry.gitlab.com/r7-platform/queue-ui"
    container_name: "demo-queue-ui"
    environment:
      - NODE_ENV=production
      - R7PLATFORM_QUEUEUI_REDIS_HOST=192.168.1.11
      - R7PLATFORM_QUEUEUI_REDIS_PASSWORD=demo
      - R7PLATFORM_QUEUEUI_REDIS_PORT=6379
      - R7PLATFORM_QUEUEUI_UI_USERNAME=xxxx
      - R7PLATFORM_QUEUEUI_UI_PASSWORD=xxxx
      - R7PLATFORM_QUEUEUI_KK_QUEUE_NAME=KHONKAEN
      - R7PLATFORM_QUEUEUI_MSK_QUEUE_NAME=MAHASARAKHAM
      - R7PLATFORM_QUEUEUI_ROIET_QUEUE_NAME=ROIET
      - R7PLATFORM_QUEUEUI_KALASIN_QUEUE_NAME=KALASIN
      - R7PLATFORM_QUEUEUI_SECRET_KEY=xxxx
      - R7PLATFORM_QUEUEUI_SUPER_SECRET_KEY=xxxx
      - R7PLATFORM_QUEUEUI_PORT=3031
    ports:
      - 3031:3031
    restart: always