version: "3.8"
services:
  queueui:
    image: "r7platform/queue-ui"
    container_name: "queueui"
    environment:
      - NODE_ENV=production
      - R7PLATFORM_QUEUEUI_REDIS_HOST=192.168.1.11
      - R7PLATFORM_QUEUEUI_REDIS_PASSWORD=demo
      - R7PLATFORM_QUEUEUI_REDIS_PORT=6379
      - R7PLATFORM_QUEUEUI_UI_USERNAME=test
      - R7PLATFORM_QUEUEUI_UI_PASSWORD=test
      - R7PLATFORM_QUEUEUI_PLATFORM_ZONE_LIST=KHONKAEN,MAHASARAKHAM,ROIET,KALASIN
      - R7PLATFORM_QUEUEUI_SECRET_KEY=xxxx
      - R7PLATFORM_QUEUEUI_SUPER_SECRET_KEY=xxxx
      - R7PLATFORM_QUEUEUI_PORT=3031
    ports:
      - 3031:3000
    restart: always