version: "3.8"
services:
  demo-queue-ui:
    image: "registry.gitlab.com/r7-platform/queue-ui"
    container_name: "demo-queue-ui"
    environment:
      - NODE_ENV=production
      - R7QUEUE_REDIS_HOST=192.168.1.11
      - R7QUEUE_REDIS_USERNAME=demo
      - R7QUEUE_REDIS_PASSWORD=demo
      - R7QUEUE_REDIS_PORT=6379
      - R7QUEUE_UI_USERNAME=xxxx
      - R7QUEUE_UI_PASSWORD=xxxx
      - R7QUEUE_KK_QUEUE_NAME=KHONKAEN
      - R7QUEUE_MSK_QUEUE_NAME=MAHASARAKHAM
      - R7QUEUE_ROIET_QUEUE_NAME=ROIET
      - R7QUEUE_KALASIN_QUEUE_NAME=KALASIN
      - R7QUEUE_SECRET_KEY=xxxx
      - R7QUEUE_SUPER_SECRET_KEY=xxxx
    ports:
      - 3333:3000
    restart: always